/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppReseauRouteImport } from './routes/_app/reseau'
import { Route as AppSystemeRouteImport } from './routes/_app/systeme'
import { Route as AppWifiRouteImport } from './routes/_app/wifi'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReseauRoute = AppReseauRouteImport.update({
  id: '/reseau',
  path: '/reseau',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSystemeRoute = AppSystemeRouteImport.update({
  id: '/systeme',
  path: '/systeme',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWifiRoute = AppWifiRouteImport.update({
  id: '/wifi',
  path: '/wifi',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/clients': typeof AppClientsRoute
  '/reseau': typeof AppReseauRoute
  '/systeme': typeof AppSystemeRoute
  '/wifi': typeof AppWifiRoute
}
export interface FileRoutesByTo {
  '/clients': typeof AppClientsRoute
  '/reseau': typeof AppReseauRoute
  '/systeme': typeof AppSystemeRoute
  '/wifi': typeof AppWifiRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/clients': typeof AppClientsRoute
  '/_app/reseau': typeof AppReseauRoute
  '/_app/systeme': typeof AppSystemeRoute
  '/_app/wifi': typeof AppWifiRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clients' | '/reseau' | '/systeme' | '/wifi'
  fileRoutesByTo: FileRoutesByTo
  to: '/clients' | '/reseau' | '/systeme' | '/wifi' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/clients'
    | '/_app/reseau'
    | '/_app/systeme'
    | '/_app/wifi'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reseau': {
      id: '/_app/reseau'
      path: '/reseau'
      fullPath: '/reseau'
      preLoaderRoute: typeof AppReseauRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/systeme': {
      id: '/_app/systeme'
      path: '/systeme'
      fullPath: '/systeme'
      preLoaderRoute: typeof AppSystemeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/wifi': {
      id: '/_app/wifi'
      path: '/wifi'
      fullPath: '/wifi'
      preLoaderRoute: typeof AppWifiRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppClientsRoute: typeof AppClientsRoute
  AppReseauRoute: typeof AppReseauRoute
  AppSystemeRoute: typeof AppSystemeRoute
  AppWifiRoute: typeof AppWifiRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppClientsRoute: AppClientsRoute,
  AppReseauRoute: AppReseauRoute,
  AppSystemeRoute: AppSystemeRoute,
  AppWifiRoute: AppWifiRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
